name: CI - Unit & Pytest

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  tests:
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.10", "3.11", "3.12"]

    defaults:
      run:
        working-directory: MLOps/Labs/Github_Labs/Lab1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: |
            MLOps/Labs/Github_Labs/Lab1/requirements.txt

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Ensure test runners exist even if not in requirements.txt
          pip install pytest

        shell: bash

      - name: Show environment
        run: |
          python --version
          pip list

      - name: Run unittest (discover)
        run: |
          python -m unittest discover -s tests -p "test_*unittest.py" -v || echo "No dedicated unittest files found; continuing"

      - name: Run pytest
        run: pytest -v

      # Optional: save transformed CSV as artifact when tests generate it
      - name: Upload processed data (if exists)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: processed-data-${{ matrix.os }}-py${{ matrix.python-version }}
          path: |
            MLOps/Labs/Github_Labs/Lab1/data/processed/**/*.csv
          if-no-files-found: ignore
