name: CI - Unit & Pytest

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest

      - name: Show environment
        run: |
          python --version
          pip list

      - name: Run unittest (discover)
        run: |
          python -m unittest discover -s test -p "test_*unittest.py" -v || echo "No dedicated unittest files found; continuing"

      - name: Run pytest
        run: pytest -v
